#!/bin/bash

# The BSD License - https://github.com/wilas/vbkick/blob/master/LICENSE

# Helps civic innovators be better developers
# Inspired by: Vagrant, Openscap, Git, vbkick and more
# Special thanks: Shawn Wells (Red Hat) https://github.com/wilas/vbkick


# Secure bash
# More about options: http://wiki.bash-hackers.org/commands/builtin/set
# treat unset variables as an error
set -u;
# exit when cmd fail (use ERR trap for clean exit)
set -e; set -E;
# fail the entire pipeline if any part of it fails
set -o pipefail;
# debug mode
#set -x;
# http://mywiki.wooledge.org/glob
shopt -s failglob;
# enable POSIX mode
# http://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html
set -o posix

# For nice printing
_GREEN="\e[1;32m"
_RED="\e[1;31m"
_YELLOW="\e[1;33m"
_NORMAL="\e[0m"
__log_info() {
    printf "[INFO] ${*}\n"
}
__log_ginfo() {
    printf "${_GREEN}[INFO] ${*}${_NORMAL}\n"
}
__log_warning() {
    printf "${_YELLOW}[WARNING] ${*}${_NORMAL}\n"
}
__log_error() {
    printf "${_RED}[ERROR] ${*}${_NORMAL}\n" >&2
}
__log_govready() {
    printf "${_GREEN}[GovReady] ${*}${_NORMAL}\n"
}

# Global preferences
VERSION="0.6.2"

# Default scap-security-guide content directory
SSGCONTENTDIR="/usr/share/xml/scap/ssg/content"

# Time at which scanning is initiated
DATE_TIME="$(date +%Y%m%d-%H%M)"

# Set location of xsl files
FILTERRESULTSFILE=".govready/xml/filterresults.xsl"
RULEIDRESULTFILE=".govready/xml/ruleidresult.xsl"

CONFIGFILE="GovReadyfile"

# Global variables - do not use it in definition file (will be overwrite during program runtime)
# name of global "private" variables should start with underscore
__init_global_state_variables(){
    # 0 - webserver is not running or kill isn't able to stop it
    _webserver_state=0
    # 0 - webserver was killed cleanly or we didn't try kill it yet
    _webserver_kill_cmd_state=0
    # during exporting tmp directory is created
    _tmp_dir=""
    # during creation VM may be temporary in inconsistent state
    # e.g. not all ports mapping, options etc. were setup
    # this flag is used to make sure that vm was created completely or not at all
}

# Display help
#@action
_usage() {
    printf "Description: the GovReady Toolkit (v${VERSION})\n"
    if $(__assert_configfile); then
        _parse_config
        __oscap_command
        if [ "$OSCAP_SSH" = true ]; then
            printf "Remote scanning enabled in GovReadyfile: ${OSCAP_COMMAND}\n"
        fi
    fi
    printf "\n"
    printf "Usage: govready <command> [<args>] \n"
    printf "\tstatus                Print basic satus information and exit\n"
    printf "\tversion               Print the version and exit\n"
    printf "\toscap_version         Print the openscap version ('oscap --v') and exit\n"
    printf "\tinit                  Initialize a GovReady directory to track scans\n"

    printf "\tinstall_epel          Install EPEL repo\n"
    printf "\tinstall_openscap      Install openSCAP\n"
    printf "\tinstall_ssg           Install openSCAP & scap-security-guide\n"
    printf "\tinstall_xsltproc      Install libxslt\n"
    
    printf "\timport <file>         Import SCAP content into scap/content/\n"
    printf "\n"

    printf "\tprofiles              Available baselines and profiles\n"
    printf "\tprofile <profile>     Update PROFILE value in GovReadyfile\n"
    printf "\tscan <profiles>       Scan system against specified profiles\n"
    printf "\tfix                   Apply most recent fix script\n"
    printf "\n"

    printf "\trule <ruleid>         Test a single rule from xccdf defined in GovReadyfile\n"
    # printf "\t list [<file>] [pass|fail|notselected|unknown|notapplicable|error]\n"
    #printf "\t                     List the rules currently returning particular result\n" 
    printf "\n"
    printf "\tcompare                Compare most recent scan results with previous\n"
    printf "\tcompare <result>       Compare most recent scan results with previous for given result value\n"
    printf "\tcompare <file1> <file2> <result>   Specify files to be compared for result value\n"

    printf "\n"
    printf "\thelp                  Print this help\n"
    printf "\n"
    printf "For help on any individual command run 'govready <command> -h'\n"
    printf "\n"
}

#@action
_context_usage(){
    case "${1}" in
        "test")
            printf "Usage: govready test <VALUE> \n"
            printf "Test passing of value\n" ;;
        *) _usage; exit ;;
    esac
}

#@special
_process_3_args() {
    # 2 args are required, 3 may be optional
    if [[ "${3}" == "-h" ]] || [[ "${4:-}" == "-h" ]]; then
        _context_usage "${1}"
        exit 0
    fi
    case "${1}" in
	"scan") shift; _govoscap "${@}" ;;
        "compare") _compare "${2}" "${3}";;
        *) _usage; exit ;;
    esac
}
 
#@special
_process_2_args() {
    # 2 args are required, 3 may be optional
    if [[ "${2}" == "-h" ]] || [[ "${3:-}" == "-h" ]]; then
        _context_usage "${1}"
        exit 0
    fi
    _Vm="${2}"
    case "${1}" in
        "test") _test ;;
        "scan") _govoscap "${2}" ;;
        "compare") _compare "${2}";;
        "import") _import "${2}" ;;
        "rule") _govoscap_rules_scan_info "${2}" ;;
        "profile") _profile_set "${2}" ;;
        *) _usage; exit ;;
    esac
}

#@special
_process_1_args() {
    # 1 arg is required
    case "${1}" in
        "list") _list_all_vms ;;
        "status") _status ;;
        "version") _prog_version ;;
        "oscap_version") _oscap_version ;;
        "init") _govready_init ;;
        "test") _test ;;
        "install_epel") _install_epel ;;
        "install_openscap") _install_openscap ;;
        "install_ssg") _install_ssg ;;
        "install_xsltproc") _install_xsltproc ;;
        "profiles") _govoscap_info ;;
        "scan") _govoscap ;;
        "compare") _compare;;
        "fix") _govoscap_fix ;;
        *) _usage; exit ;;
    esac
}

#@action
_prog_version(){
    printf "${VERSION}\n"
}

#@action
_oscap_version(){
    _parse_config
    __oscap_command
    ${OSCAP_COMMAND} --v
}

__depend_check() {
    local __dep_cmd="${1}"
    local __dep_name="${2}"
    # check whether __dep_name is installed - __dep_cmd command exist
    if ! command -v ${__dep_cmd} >/dev/null 2>&1; then
        __log_error "${__dep_cmd} command doesn't exist - install '${__dep_name}' to continue."
        return 1
    fi
}

__dependencies_check() {
    __depend_check "curl" "curl"
    __depend_check "bash" "bash"
    # __depend_check "openssl" "openssl"
    __depend_check "sed" "sed"
    __depend_check "grep" "grep"
    __depend_check "cut" "coreutils"
    __depend_check "sort" "coreutils"
    __depend_check "tail" "coreutils"
}

# Every action which requires vm settings must use this function to load them.
__load_definition() {
    __load_default_settings
    # definition.cfg is a default definition file
    # loading definition file overwrite default settings
    local __definition_fname="${1:-definition.cfg}"
    if [[ -s "${__definition_fname}" ]]; then
        # In POSIX mode the '.' and 'source' builtins do not search the current directory
        # for the filename argument if it is not found by searching PATH.
        __log_info "Loading \"${__definition_fname}\" definition..."
        if ! . "./${__definition_fname}"; then
            __log_error "Loading failed."
            return 1
        fi
    else
        __log_error "Not existing or empty \"${__definition_fname}\" file in $(pwd). Terminating..."
        return 1
    fi
    # if someone overwrite them in definition file
    __init_global_state_variables
    _vb_version=$(__get_vb_version)
    __check_required_settings
    __autoupdate_files_with_vbox_version
}

# Get virtualbox version
__get_vb_version() {
    local __version=$(VBoxManage --version) # e.g. 4.2.12r84980
    local __pos=$(expr "${__version}" : '[0-9.]\+')
    __version=${__version:0:${__pos}} #e.g. 4.2.12
    printf "${__version}"
}

__is_present() {
    local __pattern="${1:-\"${_Vm}\"}"
    VBoxManage list vms | grep -qw "${__pattern}"
}

__is_running() {
    VBoxManage showvminfo "${_Vm}" | grep -q "State:\s\+running"
}

__is_powered_off() {
    VBoxManage showvminfo "${_Vm}" | grep -q "State:\s\+powered off"
}

__is_paused() {
    VBoxManage showvminfo "${_Vm}" | grep -q "State:\s\+paused"
}

__is_alive() {
    # Alive machine may be in paused|running state
    # Useful to change state: VBoxManage controlvm "${_Vm}" pause|resume
    local __pattern="${1:-\"${_Vm}\"}"
    VBoxManage list runningvms | grep -qw "${__pattern}"
}

# checks whether port is not used by other proc
__check_port_usage() {
    local __port_nr="${1}"
    local __port_message="${2}"
    if __is_port_used ${__port_nr}; then
        __log_error "${__port_nr} port (${__port_message}) is already used by an other process."
        return 1
    fi
}

# Check whether given directory exist
__prepare_path() {
    local __path="${1}"
    local __mkdir_path="${2}"
    # Process special variables in path definition e.g. __path="%VBOXFOLDER%/%NAME%"
    local __location=$(VBoxManage list  systemproperties | grep "Default machine folder" | cut -d':' -f 2 | sed 's/^\s*//g')
    __path=${__path//%SRCPATH%/${boot_file_src_path}}
    __path=${__path//%VBOXFOLDER%/${__location}}
    __path=${__path//%PWD%/$(pwd)}
    # get homedir - $(getent passwd UID) doesn't work for MacOS; $HOME is less portable than ~
    __path=${__path//%HOME%/~}
    __path=${__path//%NAME%/${_Vm}}
    # expand a special variable - e.g. tilde (~) and
    # strips out > characters which could clobber a file during the eval
    __path=$(eval echo "${__path//>}")
    # Creates dir if necessary
    if [[ ${__mkdir_path} -eq 1 ]] && [[ ! -z "${__path}" ]] && [[ ! -d "${__path}" ]]; then
        mkdir -p "${__path}"
    fi
    # Return __path
    printf "${__path}"
}

__curl_safe() {
    local __src="${1}"
    local __dest="${2}"
    local __statuscode=$(curl -Lkfw "%{http_code}\n" "${__src}" -o "${__dest}")
    if [[ ${__statuscode} -ne 200 ]]; then
        __log_error "${__src} status code is ${__statuscode}. Terminating..."
        return 1
    fi
}


#
# GovReady Methods
# 

#@action
_install_epel(){
    if [ ! -f /etc/yum.repos.d/epel.repo ]
    then
        __log_warning "installing epel repo "
        wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
        rpm -Uvh epel-release-6*.rpm
    else 
        __log_ginfo "epel already installed"
    fi
}

#@action\
_install_openscap(){
    # todo : add checks for distribution
    if [ ! -f /etc/yum.repos.d/epel-6-openscap.repo ]
    then
        __log_warning "OpenSCAP repo not installed, installing"
        local NOPKGMANAGER=FALSE

        if which yum &> /dev/null; then
            _install_epel
            __log_govready "installing OpenSCAP on via yum (CentOS/Fedora/RedHat)"
            __log_govready "Running command: yum install openscap openscap-utils -y"
            yum install openscap openscap-utils -y
        elif which apt-get &> /dev/null; then
            __log_ginfo "installing OpenSCAP on via apt-get (Ubuntu)"
            __log_ginfo "attempting libopenscap8 for 14.04, fallback to libopenscap1 for 12.04"
            __log_govready "Running command: apt-get install libopenscap8 -y || apt-get install libopenscap1 -y"
            apt-get install libopenscap8 -y || apt-get install libopenscap1 -y
            # install lynx
            __log_ginfo "install lynx browser"
            __log_govready "Running command: apt-get install lynx -y"
            apt-get install lynx -y
        else
            local NOPKGMANAGER=TRUE
            __log_error "Neither apt-get or yum package manager found. Unable to install software packages."
            exit 1
        fi
    else
        __log_ginfo "OpenSCAP already installed"
    fi
}

#@action
_install_ssg(){
    if ! rpm -qa | grep -q scap-security-guide 
    then
        __log_ginfo "scap-security-guide not installed"
        local NOPKGMANAGER=FALSE

        if which yum &> /dev/null; then
            # install with yum on RHEL/CentOS/Fedora
            _install_epel
            __log_govready "Installing scap-security-guide on via yum (CentOS/Fedora/RedHat)"
            __log_govready "Running command: yum install openscap openscap-utils scap-security-guide lynx -y"
            yum install openscap openscap-utils scap-security-guide lynx -y
        elif which apt-get &> /dev/null; then
            __log_ginfo "Installing scap-security-guide on via apt-get (Ubuntu)"
            __log_ginfo "Attempting libopenscap8 for 14.04, fallback to libopenscap1 for 12.04"
            __log_govready "Running command: apt-get install libopenscap8 -y || apt-get install libopenscap1 -y"
            apt-get install libopenscap8 -y || apt-get install libopenscap1 -y
            # Install lynx
            __log_ginfo "Install lynx browser"
            __log_govready "Running command: apt-get install lynx -y"
            apt-get install lynx -y
        else
            local NOPKGMANAGER=TRUE
            __log_error "Neither apt-get or yum package manager found. Unable to install software packages."
            exit 1
        fi
    else
        __log_ginfo "scap-security-guide already installed"
    fi
}

#@action
_install_xsltproc() {
#    if ! rpm -qa | grep -q libxslt
#    then
        __log_ginfo "libxslt required for xsltproc"
        local NOPKGMANAGER=FALSE

        if which yum &> /dev/null; then
            # install with yum on RHEL/CentOS/Fedora
            __log_govready "installing libxslt on via yum (CentOS/Fedora/RedHat)"
            __log_govready "Running command: yum install libxslt -y"
            yum install libxslt -y
        elif which apt-get &> /dev/null; then
            __log_ginfo "installing xsltproc on via apt-get (Ubuntu)"
            # __log_ginfo "attempting libopenscap8 for 14.04, fallback to libopenscap1 for 12.04"
            __log_govready "Running command: apt-get install xsltproc -y"
            apt-get install xsltproc -y
        else
            local NOPKGMANAGER=TRUE
            __log_error "Neither apt-get or yum package manager found. Unable to install software packages."
            exit 1
        fi
#    else
#        __log_ginfo "libxslt already installed"
#    fi
}

#@action
_govready_init(){
    __log_info "Initializing GovReady directory"

    __log_info "Creating default GovReadyfile"
    GRF="
# Welcome to the GovReadyfile
#
# Almost every govready command parses and uses the parameters stored in this file.
# Having parameters and values stored in this file simplifies what must be typed at
# the command line and creates shareable artifact supporting Infrastructure as Code.

# GovReady API/syntax version. You should not change this unless you are very certain
API = 0.1.0

# Base directory under which all scan and eval results will be written
SCANDIR = scans

# Default profile to be used with 'govready scan' command
PROFILE = test

# All three vars must be set 'OSCAP_USER@OSCAP_HOST OSCAP_PORT' for remote scanning
# OSCAP_USER = root
# OSCAP_HOST = example.com
# OSCAP_PORT = 22

# If set, overrides default = /usr/share/xml/scap/ssg/content
# TODO: prepend to other paths if they are not absolute
# SSGCONTENTDIR="/usr/share/xml/scap/ssg/content"

# CPE file to be used with scans. Change this line to use a dictionary for a specific platform.
# Currently, the dictionaly must be on the file system.
# It is recommended new CPE dictionaries be added to the 'scap/content' directory
CPE = /usr/share/xml/scap/ssg/content/ssg-rhel6-cpe-dictionary.xml

# XCCDF file to be used with scans. Change this line to use a different XCCDF.
XCCDF = /usr/share/xml/scap/ssg/content/ssg-rhel6-xccdf.xml

# Directory into which to save files using 'govready import' command
IMPORTDIR = scap/content

"
    echo "$GRF" > GovReadyfile

    # Parse the GovReadyfile just created and use values to put things in the proper place
    _parse_config
    mkdir -p "${SCANDIR}"

    # Create .govready files
    __log_info "Creating .govready subdirectories and files"
    mkdir -p .govready/scans
    mkdir -p .govready/xml
    _govready_init_scaninfo_file
    _govready_init_scanruleinfo_file
    _govready_init_getruleovaldef_file
    _govready_init_ruleidresult_file
    _govready_init_filterresults_file
    touch .govready/config
    touch .govready/log

    # Create directory for new scap content
    # To Do: Make this a GovReadyfile parameter
    mkdir -p scap/content
}

#@action
_govready_init_scaninfo_file() {

    __log_info "Creating .govready/xml/scaninfo.xsl file"

    # Important to include `!` to avoid sending a halt program signal
    ! read -d '' SIF <<"EOF"
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.1"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:cdf="http://checklists.nist.gov/xccdf/1.1"
    xmlns:exsl="http://exslt.org/common"
    xmlns:db="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://docbook.org/ns/docbook"
    xmlns:s="http://open-scap.org/"
    exclude-result-prefixes="xsl cdf db s exsl"
    xmlns:ovalres="http://oval.mitre.org/XMLSchema/oval-results-5"
    xmlns:sceres="http://open-scap.org/page/SCE_result_file"
    >

<!--
****************************************************************************************

Copyright: Greg Elin, 2014

This file provides a relitvely simple xslt transformation on openscap results.xml file
to show pass / fail numbers. 

usage: $> xsltproc scaninfo.xsl result-file-name.xml

-->

<!--xsl:output method="xml" encoding="UTF-8" indent="yes"/-->    
<xsl:strip-space elements="*"/>
<xsl:output method="text" encoding="utf-8" />

<xsl:template match="/">
    <xsl:apply-templates/>
</xsl:template>

<xsl:template match='cdf:TestResult'>
OpenSCAP NIST Certified SCAP Scanner Results for Profile "<xsl:value-of select='cdf:profile/@idref'/>"

The "<xsl:value-of select='cdf:profile/@idref'/>" profile identifies <xsl:value-of select='count(cdf:rule-result[@severity="high"][cdf:result="pass"] | cdf:rule-result[@severity="high"][cdf:result="fail"] | cdf:rule-result[@severity="high"][cdf:result="error"])' /> high severity controls. OpenSCAP says <xsl:value-of select='count(cdf:rule-result[@severity="high"][cdf:result="pass"])' /> passing and <xsl:value-of select='count(cdf:rule-result[@severity="high"][cdf:result="fail"])' /> failing.
The "<xsl:value-of select='cdf:profile/@idref'/>" profile identifies <xsl:value-of select='count(cdf:rule-result[@severity="medium"][cdf:result="pass"] | cdf:rule-result[@severity="medium"][cdf:result="fail"] | cdf:rule-result[@severity="medium"][cdf:result="error"])' /> medium severity controls. OpenSCAP says <xsl:value-of select='count(cdf:rule-result[@severity="medium"][cdf:result="pass"])' /> passing and <xsl:value-of select='count(cdf:rule-result[@severity="medium"][cdf:result="fail"])' /> failing.
The "<xsl:value-of select='cdf:profile/@idref'/>" profile identifies <xsl:value-of select='count(cdf:rule-result[@severity="low"][cdf:result="pass"] | cdf:rule-result[@severity="low"][cdf:result="fail"] | cdf:rule-result[@severity="low"][cdf:result="error"])' /> low severity controls. OpenSCAP says <xsl:value-of select='count(cdf:rule-result[@severity="low"][cdf:result="pass"])' /> passing and <xsl:value-of select='count(cdf:rule-result[@severity="low"][cdf:result="fail"])' /> failing.
<xsl:text>
</xsl:text>
</xsl:template>

<!-- include to stop leakage from builtin tempaltes -->
<xsl:template match='node()' mode='engine-results'/>
<xsl:template match="text()"/>

</xsl:stylesheet>

EOF

    echo "$SIF" > .govready/xml/scaninfo.xsl

}

#@action
_govready_init_scanruleinfo_file() {

    __log_info "Creating .govready/xml/ruleinfo.xsl file"

    # Important to include `!` to avoid sending a halt program signal
    ! read -d '' SIF <<"EOF"
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.1"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:cdf="http://checklists.nist.gov/xccdf/1.1"
    xmlns:exsl="http://exslt.org/common"
    xmlns:db="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://docbook.org/ns/docbook"
    xmlns:s="http://open-scap.org/"
    exclude-result-prefixes="xsl cdf db s exsl"
    xmlns:ovalres="http://oval.mitre.org/XMLSchema/oval-results-5"
    xmlns:sceres="http://open-scap.org/page/SCE_result_file"
    >

<!--
****************************************************************************************

Copyright: Greg Elin, 2014

This file provides a relitvely simple xslt transformation on openscap results.xml file
to show information regarding a single rule.

usage: $> xsltproc - -stringparam paramname paramvalue ruleinfo.xsl result-file-name.xml

-->

<xsl:param name="ruleid">notdefined</xsl:param>
<xsl:strip-space elements="*"/>
<xsl:output method="text" encoding="utf-8" />

<xsl:template match="/">
    <xsl:apply-templates/>
</xsl:template>

<xsl:template match="cdf:rule-result">
<xsl:if test="@idref=$ruleid">
Rule "<xsl:value-of select='@idref'/>" (AKA <xsl:value-of select='cdf:ident[@system="http://cce.mitre.org"]'/>) had result "<xsl:value-of select='cdf:result'/>" in most recent scan.
The oval definition is "<xsl:value-of select='(cdf:check[@system="http://oval.mitre.org/XMLSchema/oval-definitions-5"]/cdf:check-content-ref/@name)'/>" in file "<xsl:value-of select='(cdf:check[@system="http://oval.mitre.org/XMLSchema/oval-definitions-5"]/cdf:check-content-ref/@href)'/>" 

Evaluate rule's oval test: govready rule <xsl:value-of select='@idref'/>
OpenSCAP oval eval command: oscap oval eval --id <xsl:value-of select='(cdf:check[@system="http://oval.mitre.org/XMLSchema/oval-definitions-5"]/cdf:check-content-ref/@name)'/> --variables scans/variables.xml /usr/share/xml/scap/ssg/content/<xsl:value-of select='(cdf:check[@system="http://oval.mitre.org/XMLSchema/oval-definitions-5"]/cdf:check-content-ref/@href)'/>

<xsl:text>
</xsl:text>
</xsl:if>
</xsl:template>

<!-- include to stop leakage from builtin tempaltes -->
<xsl:template match='node()' mode='engine-results'/>
<xsl:template match="text()"/>

</xsl:stylesheet>

EOF

    echo "$SIF" > .govready/xml/ruleinfo.xsl

}

#@action
_govready_init_getruleovaldef_file() {

    __log_info "Creating .govready/xml/getruleovaldef.xsl file"

    # Important to include `!` to avoid sending a halt program signal
    ! read -d '' SIF <<"EOF"
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.1"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:cdf="http://checklists.nist.gov/xccdf/1.1"
    xmlns:exsl="http://exslt.org/common"
    xmlns:db="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://docbook.org/ns/docbook"
    xmlns:s="http://open-scap.org/"
    exclude-result-prefixes="xsl cdf db s exsl"
    xmlns:ovalres="http://oval.mitre.org/XMLSchema/oval-results-5"
    xmlns:sceres="http://open-scap.org/page/SCE_result_file"
    >

<!--
****************************************************************************************

Copyright: Greg Elin, 2014

This file provides a relitvely simple xslt transformation on openscap results.xml file
to show information regarding a single rule.

usage: $> xsltproc - -stringparam paramname paramvalue ruleinfo.xsl result-file-name.xml

-->

<xsl:param name="ruleid">notdefined</xsl:param>
<xsl:strip-space elements="*"/>
<xsl:output method="text" encoding="utf-8" />

<xsl:template match="/">
    <xsl:apply-templates/>
</xsl:template>

<xsl:template match="cdf:rule-result">
<xsl:if test="@idref=$ruleid">
<xsl:value-of select='(cdf:check[@system="http://oval.mitre.org/XMLSchema/oval-definitions-5"]/cdf:check-content-ref/@name)'/>
</xsl:if>
</xsl:template>

<!-- include to stop leakage from builtin tempaltes -->
<xsl:template match='node()' mode='engine-results'/>
<xsl:template match="text()"/>

</xsl:stylesheet>

EOF

    echo "$SIF" > .govready/xml/getruleovaldef.xsl

}

#@special
__assert_configfile(){
    [[ -r "$CONFIGFILE" ]]
}

#@action
_parse_config(){
    # Check if GovReadyFile exists
    if $(! __assert_configfile); then 
        __log_error "Missing GovReadyfile"
        echo "Missing GovReadyfile. Did you forget to 'govready init'?"
        exit 1
    fi

    # Following sed should find only lines with an `=`, ignore blank lines, and ignore bad code
    eval $(sed '/^[:space:]*#/d;/^[:space:]*$/d;s/=/ /;' < "$CONFIGFILE" | while read -r key val
    do
        # Only allow safe characters
        val=$(echo "$val" | sed 's/[^-[:alnum:]\.\/]//g')
        str="$key='$val'"
        echo "$str"
    done)
}

# This relies on values provided by _parse_config so must come after it
#@special
__oscap_command() {
    if [ -n "${OSCAP_USER+x}" ] && [ -n "${OSCAP_HOST+x}" ] && [ -n "${OSCAP_PORT+x}" ]; then
        OSCAP_COMMAND="oscap-ssh ${OSCAP_USER}@${OSCAP_HOST} ${OSCAP_PORT}"
	RESULTS_DIR=${SCANDIR}/${PROFILE}-${OSCAP_HOST}
	SSH_HOST="${OSCAP_USER}@${OSCAP_HOST}"
	SSH_PORT=${OSCAP_PORT}
        OSCAP_SSH=true
    else
        OSCAP_COMMAND="oscap"
	RESULTS_DIR=${SCANDIR}/${PROFILE}
        OSCAP_SSH=false
    fi
}

#@action
_test() {
    __log_warning "Test command"
    printf "\n"
}

#@action
_govoscap_info() {
    _parse_config
    __oscap_command
    # list available profiles
    __log_govready "Profiles are listed in output of information in xccdf file" 
    local oscap_command="${OSCAP_COMMAND} info ${XCCDF}"
    __log_govready "Running command: ${oscap_command}"
    eval $oscap_command || __log_govready "..."
}

#@action
_govoscap() {
    # usage: _govoscap("stig-rhel6-server-upstream")
    
    _parse_config
    __oscap_command
    #__depend_check "libxslt" "xsltrpoc"  # Used to generate quick reports at commandline

    EXTRAS=''
    # overwrite values from GovReadyfile with command line values
    if [ "$#" -eq 0 ]; then
        __log_govready "Using profile ${PROFILE}.\n"
        profile="${PROFILE}"
    else
	if [ "${1}" = "GovReadyfile" ]; then
	    __log_govready "Using profile ${PROFILE}.\n"
            profile="${PROFILE}"
	    shift
	    EXTRAS="${@}"
	else
            profile="${1}"
	fi
    fi

    # set params
    local xccdffile="${XCCDF}"

    # set up results directories
    if [ "$OSCAP_SSH" = true ]; then
        #local oval_or_arf="--results-arf ${RESULTS_DIR}/${DATE_TIME}-arf.xml"
        local oval_or_arf="--cpe ${CPE}"
    else
        local oval_or_arf="--oval-results --cpe ${CPE}"
    fi
    echo "Placing scan results in ${RESULTS_DIR}..."
    mkdir -p ${RESULTS_DIR}

    # build and execute openscap eval
    local scan_command="${OSCAP_COMMAND} xccdf eval --profile ${profile} ${oval_or_arf} --results ${RESULTS_DIR}/${DATE_TIME}-results.xml --report ${RESULTS_DIR}/${DATE_TIME}-results.html ${xccdffile} ${EXTRAS}"
    __log_govready "Scanning system for compliance to profile ${profile}"
    __log_govready "Running command: ${scan_command}"
    eval $scan_command || __log_govready "..."
    
    # make results readable
    chmod go+r ${RESULTS_DIR}/${DATE_TIME}-results.html
    chmod go+r ${RESULTS_DIR}/${DATE_TIME}-results.xml

    # build and execute openscap fix file generation
    local fix_command="oscap xccdf generate fix --result-id xccdf_org.open-scap_testresult_$profile ${RESULTS_DIR}/${DATE_TIME}-results.xml > ${RESULTS_DIR}/${DATE_TIME}-fix.sh"
    __log_govready "Running command: \"${fix_command}\""
    eval $fix_command || __log_govready "..."

    # export variables from scan
    # oscap oval eval --variables ssg-rhel6-oval.xml-0.variables-0.xml --id oval:ssg:def:1223 /usr/share/xml/scap/ssg/content/ssg-rhel6-oval.xml
    local export_command="oscap xccdf export-oval-variables --profile ${profile} --cpe ${CPE} ${xccdffile}"
    __log_govready "Running command: \"${export_command}\""
    eval $export_command || __log_govready "..."
    # mv exported variables file
    local bash_command="mv ssg-rhel6-oval.xml-0.variables-0.xml ${RESULTS_DIR}/${DATE_TIME}-variables.xml"
    __log_govready "Running command: \"${bash_command}\""
    eval $bash_command || __log_govready "..."

    # set results-previous softlinks if they exist
    [ -f ${RESULTS_DIR}/results.xml ] && ln -sf $(readlink ${RESULTS_DIR}/results.xml) ${RESULTS_DIR}/results-previous.xml || __log_govready "..."
    [ -f ${RESULTS_DIR}/results.html ] && ln -sf $(readlink ${RESULTS_DIR}/results.html) ${RESULTS_DIR}/results-previous.html || __log_govready "..."
    [ -f ${RESULTS_DIR}/fix.sh ] && ln -sf $(readlink ${RESULTS_DIR}/fix.sh) ${RESULTS_DIR}/fix-previous.sh || __log_govready "..."
    [ -f ${RESULTS_DIR}/variables.xml ] && ln -sf $(readlink ${RESULTS_DIR}/variables.xml) ${RESULTS_DIR}/variables-previous.xml || __log_govready "..."
    # set results softlinks
    ln -sf ${DATE_TIME}-results.xml ${RESULTS_DIR}/results.xml
    ln -sf ${DATE_TIME}-results.html ${RESULTS_DIR}/results.html
    ln -sf ${DATE_TIME}-fix.sh ${RESULTS_DIR}/fix.sh
    ln -sf ${DATE_TIME}-variables.xml ${RESULTS_DIR}/variables.xml

    # build and execute govready commandline quick report
    local gov_command="xsltproc .govready/xml/scaninfo.xsl ${RESULTS_DIR}/results.xml"
    __log_govready "Printing quickie report..."
    __log_govready "Running command: \"${gov_command}\""
    eval $gov_command || __log_govready "..."

    # send govready hint to commandline
    printf "View detailed HTML report: lynx ${RESULTS_DIR}/results.html\n"
    printf "Run auto-generated fix file: govready fix \n\n"
}

#@action
_govoscap_fix() {
    # Function uses symbolic link to run the most recently generated fix script

    # Todo: enable passing of specific fix script target
    _parse_config
    __oscap_command
    #__depend_check "libxslt" "xsltrpoc"  # Used to generate quick reports at commandline
 
    # set params
    local fixfile="${RESULTS_DIR}/$(readlink ${RESULTS_DIR}/fix.sh)"

    # graceful error if fix file does not exist
    if [ ! -f $fixfile ]
    then
        __log_warning "No fix file yet exists in ${RESULTS_DIR}"
        printf "No fix file exists. Have you run a 'govready scan' yet?\n"
    else
        # execute most recent fix file
        __log_govready "Executing most recent fix file: ${fixfile}"
	if [ "$OSCAP_SSH" = true ]; then
	    _govoscap_fix_remote "$fixfile"
	else
            bash $fixfile
	fi
    fi
}

#@action
_govoscap_fix_remote() {
    local fixfile="${1}"
    local fixbase=`basename ${fixfile}`
    local fixoutput="${fixbase%.sh}.txt"
    
    echo "Connecting to '$SSH_HOST' on port '$SSH_PORT'..."
    MASTER_SOCKET_DIR=$(mktemp -d)
    MASTER_SOCKET="$MASTER_SOCKET_DIR/ssh_socket"
    ssh -M -f -N -o ServerAliveInterval=60 -o ControlPath=$MASTER_SOCKET -p "$SSH_PORT" "$SSH_HOST" || die "Failed to connect!"
    
    echo "Connected!  Creating remote temporary directory..."
    REMOTE_TEMP_DIR=$(ssh -o ControlPath=$MASTER_SOCKET -p "$SSH_PORT" "$SSH_HOST" mktemp -d) || die "Failed to create remote temporary directory!"

    echo "Copying '$fixfile' to remote working directory '$REMOTE_TEMP_DIR/${fixbase}'..."
    scp -o ControlPath=$MASTER_SOCKET -P "$SSH_PORT" "$fixfile" "$SSH_HOST:${REMOTE_TEMP_DIR}/${fixbase}" || die "Failed to copy fix file to remote temporary directory!"

    echo "Executing '$fixbase' on $SSH_HOST and saving the output..."
    ssh -o ControlPath=$MASTER_SOCKET -p "$SSH_PORT" "$SSH_HOST" "bash ${REMOTE_TEMP_DIR}/${fixbase} | tee ${REMOTE_TEMP_DIR}/${fixoutput}"

    echo "Saving fixfile output to ${RESULTS_DIR}/${fixoutput}..."
    scp -o ControlPath=$MASTER_SOCKET -P "$SSH_PORT" "$SSH_HOST:${REMOTE_TEMP_DIR}/${fixoutput}" "${RESULTS_DIR}/${fixoutput}" || die "Failed to copy the fixout file back to local machine!"

    echo "Removing remote temporary directory..."
    ssh -o ControlPath=$MASTER_SOCKET -p "$SSH_PORT" "$SSH_HOST" "rm -r $REMOTE_TEMP_DIR" || die "Failed to remove remote temporary directory!"
    
    echo "Disconnecting ssh and removing master ssh socket directory..."
    ssh -o ControlPath=$MASTER_SOCKET -p "$SSH_PORT" "$SSH_HOST" -O exit || die "Failed to disconnect!"
    rm -r "$MASTER_SOCKET_DIR" || die "Failed to remove local master SSH socket directory!"
}

_govoscap_rules_scan_info() {
    # Provide feedback on a current scan
    _parse_config
    # Expects a scan result to be provided
    ruleid=${1}
    __log_govready "Checking scan results for rule ${ruleid} to scap/content"

    # If no scan result provided, return error and end processing
    local bash__command="xsltproc --stringparam ruleid ${ruleid} .govready/xml/ruleinfo.xsl ${SCANDIR}/results.xml"
    __log_govready "Running command: \"${bash__command}\""
    eval $bash__command || __log_govready "..."

    # build and execute oval eval for a rule id
    # get rule oval def
    ruleid_ovaldef=$(xsltproc --stringparam ruleid ${ruleid} .govready/xml/getruleovaldef.xsl scans/results.xml)
    local oscap__command="oscap oval eval --id ${ruleid_ovaldef} --variables scans/variables.xml ${SSGCONTENTDIR}/ssg-rhel6-oval.xml"
    __log_govready "Running command: \"${oscap__command}\""
    eval $oscap__command || __log_govready "..."

}

#@action
_compare() {

    _parse_config

    local __args_num=$#
    if [[ ${__args_num} -eq 0 ]]; then
        # compare results.xml to results-previous.xml
        newresults="${SCANDIR}/results.xml"
        oldresults="${SCANDIR}/results-previous.xml"
        result="pass"
    elif [[ ${__args_num} -eq 1 ]]; then
        # compare results.xml to results-previous.xml for passed result
        newresults="${SCANDIR}/results.xml"
        oldresults="${SCANDIR}/results-previous.xml"
        result="pass"
        if [[ $1 = "fail" || $1 = "pass" || $1 = "error" || $1 = "unknown" || $1 = "notapplicable" || $1 = "notselected" ]]; then
            result=$1
        else
            __log_error "govready compare ${1} is incorrect. Did you mean 'govready compare pass' or 'govready file1 file2 pass?"
            exit 1
        fi
    elif [[ ${__args_num} -eq 2 ]]; then
        newresults=$1
        oldresults=$2
        #result="pass"
        result="notdefined"
    elif [[ ${__args_num} -eq 3 ]]; then
        newresults=$1
        oldresults=$2
        if [[ $3 = "fail" || $3 = "pass" || $3 = "error" || $3 = "unknown" || $3 = "notapplicable" || $3 = "notselected" ]]; then
            result=$3
        else
            __log_error "govready compare ${3} is incorrect. Did you mean 'govready compare pass' or 'govready file1 file2 pass?"
            exit 1
        fi
    fi

    # Set location of xsl files
    # FILTERRESULTSFILE=".govready/xml/filterresults.xsl"
    # RULEIDRESULTFILE=".govready/xml/ruleidresult.xsl"

    cmd="xsltproc --stringparam result $result $FILTERRESULTSFILE $newresults"
    echo "command: $cmd"
    rules=$(eval $cmd)

    printf "\nComparing $result results...\nA: $newresults  vs  B: $oldresults\n\n"

    for ruleid in $rules; do
        # get result for a ruleid from new results
        cmd_newresults='xsltproc --stringparam ruleid "${ruleid}" $RULEIDRESULTFILE $newresults'
        newtestresult=$(eval $cmd_newresults)

        # get result for a ruleid from old results
        cmd_oldresults='xsltproc --stringparam ruleid "${ruleid}" $RULEIDRESULTFILE $oldresults'
        oldtestresult=$(eval $cmd_oldresults)

        # print out comparison
        if [ $newtestresult = "pass" ]; then
            printf "A: ${_GREEN}$newtestresult${_NORMAL}  "
        else
            printf "A: ${_RED}$newtestresult${_NORMAL}  "
        fi

        if [ $oldtestresult = "pass" ]; then
            printf "B: ${_GREEN}$oldtestresult${_NORMAL}  "
        else
            printf "B: ${_RED}$oldtestresult${_NORMAL}  "
        fi

        printf "rule = $ruleid\n"


        #if [ $oldtestresult != $newtestresult ]; then
        #   printf "A: ${newtestresult} where B: ${oldtestresult} for rule: $ruleid"
        #fi
    done
}

#@action
_import() {
    _parse_config
    local importdir="${IMPORTDIR}"
    
    __log_govready "Importing ${1} to ${importdir}"
    filename=$(basename "${1}")
    wget --no-check-certificate "${1}" --output-document "${importdir}/${filename}"
    echo "saved ${importdir}/${filename}"
    # unzip if zip file
    if [ ${filename: -4} == ".zip" ]; then
        # unzip file
        unzip "scap/content/${filename}" -d "scap/content/" && rm "${importdir}/${filename}"
        echo "unzipped ${importdir}/${filename}"
    fi
}

#@action
_profile_set() {
    _parse_config
    __log_govready "Updating scan profile to ${1}"
    sed -ir s/"^PROFILE.*"/"PROFILE = ${1}"/g GovReadyfile
}

#@action
_status() {
    _parse_config
    _prog_version
    __oscap_command
    echo "Scan profile: ${PROFILE}"
    echo "CPE file: ${CPE}"
    echo "XCCDF file: ${XCCDF}"
    echo "XCCDF file: ${XCCDF}"
    echo "OSCAP command: $OSCAP_COMMAND"
}

# (signals and error handler) - cleaning after ctr-c, etc.
#@special
_clean_up() {
    __log_info "Signal handler - cleanup before exiting..."
    # run _on_exit function to make real cleaning
    exit 1
}

#@special
_on_exit(){
    # this is a finally block - exec always on exit
    # if [[ ${_webserver_kill_cmd_state} -eq 0 ]]; then
    #     # stop webserver (only if __stop_web_server function didn't fail previuosly)
    #     __stop_web_server
    # else
    #     # previuosly executed __stop_web_server function fail in killing $_web_pid
    #     __log_warning "problem with killing webserver (proc ${_web_pid}). Kill process manually."
    # fi
    # clean _tmp_dir if exist
    if [[ -d ${_tmp_dir} ]]; then
        rm -rf ${_tmp_dir}
    fi
    # help recover some changes made on VM during exporting
    #__recover_vm_state
}

#@special
_main() {
    local __args_num=$#
    __init_global_state_variables
    if [[ ${__args_num} -eq 1 ]]; then
        # check whether we have everything to start with govready
        __dependencies_check
        _process_1_args "${1}"
    elif [[ ${__args_num} -eq 2 ]]; then
        # check whether we have everything to start with govready
        __dependencies_check
        _process_2_args "${1}" "${2}"
    elif [[ ${__args_num} -gt 2 ]] || [[ ${__args_num} -eq 4 ]]; then
        # check whether we have everything to start with govready
        __dependencies_check
        _process_3_args "${@}"
    else
        # wrong number of arguments
        _usage
        exit 1
    fi
}


## template files ##
#@action
_govready_init_ruleidresult_file() {

    __log_info "Creating .govready/xml/ruleidresult.xsl file"

    # Important to include `!` to avoid sending a halt program signal
    ! read -d '' SIF <<"EOF"
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.1"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:cdf="http://checklists.nist.gov/xccdf/1.1"
    xmlns:exsl="http://exslt.org/common"
    xmlns:db="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://docbook.org/ns/docbook"
    xmlns:s="http://open-scap.org/"
    exclude-result-prefixes="xsl cdf db s exsl"
    xmlns:ovalres="http://oval.mitre.org/XMLSchema/oval-results-5"
    xmlns:sceres="http://open-scap.org/page/SCE_result_file"
    >

<!--
****************************************************************************************

Copyright: Greg Elin, 2014

This file provides a relitvely simple xslt transformation on openscap results.xml file
to show information regarding a single rule.

usage: $> xsltproc - -stringparam paramname paramvalue ruleidresult.xsl result-file-name.xml

-->

<xsl:param name="ruleid">notdefined</xsl:param>
<xsl:param name="compare_result">notdefined</xsl:param>
<xsl:strip-space elements="*"/>
<xsl:output method="text" encoding="utf-8" />

<xsl:template match="/">
    <xsl:apply-templates/>
</xsl:template>

<xsl:template match="cdf:rule-result">
<xsl:if test="@idref=$ruleid">
    <xsl:value-of select='cdf:result'/>
<xsl:text>
</xsl:text>
</xsl:if>
</xsl:template>

<!-- include to stop leakage from builtin tempaltes -->
<xsl:template match='node()' mode='engine-results'/>
<xsl:template match="text()"/>

</xsl:stylesheet>

EOF

    echo "$SIF" > .govready/xml/ruleidresult.xsl

}

#@action
_govready_init_filterresults_file() {

    __log_info "Creating .govready/xml/filterresults.xsl file"

    # Important to include `!` to avoid sending a halt program signal
    ! read -d '' SIF <<"EOF"
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:cdf="http://checklists.nist.gov/xccdf/1.1"
    xmlns:exsl="http://exslt.org/common"
    xmlns:db="http://docbook.org/ns/docbook"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://docbook.org/ns/docbook"
    xmlns:s="http://open-scap.org/"
    exclude-result-prefixes="xsl cdf db s exsl"
    xmlns:ovalres="http://oval.mitre.org/XMLSchema/oval-results-5"
    xmlns:sceres="http://open-scap.org/page/SCE_result_file"
    >

<!--
****************************************************************************************

Copyright: Greg Elin, 2014

This style sheet lists all failed rules

usage: $> xsltproc - -stringparam paramname paramvalue filterresults.xsl result-file-name.xml
examples
    Which rules pass in most recent scan?
       xsltproc - -stringparam result pass filterresults.xsl scans/results.xml

    Which rules fail in most recent scan?
       xsltproc - -stringparam result fail filterresults.xsl scans/results.xml

    Compare all results that are other than "notselected" 
       xsltproc filterresults.xsl scans/results.xml

-->

<xsl:param name="result">notdefined</xsl:param>
<xsl:strip-space elements="*"/>
<xsl:output method="text" encoding="UTF-8" />

<xsl:template match="/">
    <xsl:apply-templates/>
</xsl:template>

<xsl:template match="/">
<xsl:choose>
  <xsl:when test="$result = 'notdefined'">
    <xsl:for-each select='cdf:Benchmark/cdf:TestResult/cdf:rule-result[cdf:result != "notselected"]'>
      <xsl:value-of select="@idref"/>
    <xsl:text>
</xsl:text>
   </xsl:for-each>
  </xsl:when>
  <xsl:otherwise>
    <xsl:for-each select='cdf:Benchmark/cdf:TestResult/cdf:rule-result[cdf:result = $result]'>
      <xsl:value-of select="@idref"/>
    <xsl:text>
</xsl:text>
    </xsl:for-each>
  </xsl:otherwise>
</xsl:choose>

</xsl:template>
<!-- include to stop leakage from builtin tempaltes -->
<xsl:template match='node()' mode='engine-results'/>
<xsl:template match="text()"/>

</xsl:stylesheet>


EOF

    echo "$SIF" > .govready/xml/filterresults.xsl

}


## MAIN ##
# signals and errors handler
trap _clean_up SIGHUP SIGINT SIGTERM ERR
trap _on_exit EXIT
_main "${@}"
