'\" t
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.TH "GOVREADY" "1" "7 September 2014" "0.1" "govready man page"
.SH "NAME"
govready - FISMA IT Compliance accreditation helper toolkit.
.SH "SYNOPSIS"
.BI govready " <command> [args]"
.SH "DESCRIPTION"
.PP
\fBgovready\fR is an open source and easy in use tool for scanning operating systems and software for compliance to hardened baseline configurations expressed in SCAP. \fBgovready\fR is a wrapper around OpenSCAP NIST certified SCAP content scanner and provides additional functionality to make OpenSCAP easier to use and makes securing a system a more iterative and collaborative experience. \fBgovready\fR is light weight and written in bash in order to be transparent to users.
.PP
